allowBuilds:
  core-js: true
  cpu-features: true
  esbuild: true
  msw: true
  protobufjs: true
  ssh2: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vitest: 4.1.9
  vite-plus: 0.2.1
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
